# Generated by Django 4.1.2 on 2022-10-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitas_homepage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch_visita', models.DateTimeField(auto_now=True)),
                ('ip_visita', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'VisitasHomepage',
                'verbose_name_plural': 'VisitasHomepages',
            },
        ),
    ]
