# Generated by Django 4.1.2 on 2022-10-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitas_homepage',
            new_name='visitas',
        ),
    ]
