# Generated by Django 4.1.2 on 2022-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_visitas_options_visitas_navegador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch_visita', models.DateTimeField(auto_now=True)),
                ('ip_visita', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicación_visita', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname_visitante', models.CharField(blank=True, max_length=255, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'HomepageVisitas',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='visitas',
        ),
    ]
