# Generated by Django 4.1.2 on 2022-10-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100, unique=True, verbose_name='Nombre Departamento')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('id_pantalla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pantalla', models.CharField(max_length=100, unique=True, verbose_name='Pantalla')),
            ],
            options={
                'verbose_name_plural': 'Pantallas',
                'ordering': ['id_pantalla'],
            },
        ),
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tiene_permisos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Perfil de Usuarios',
                'ordering': ['id_rol'],
            },
        ),
        migrations.CreateModel(
            name='Politica_Seguridad',
            fields=[
                ('id_politica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_politica', models.CharField(blank=True, max_length=50)),
                ('tiempo_cambio_password', models.IntegerField(blank=True, default=90, null=True, verbose_name='Frecuencia en Días de Cambio de Contraseña')),
                ('tiempo_inactividad_sesion', models.CharField(choices=[('1', '5 Minutos'), ('2', '10 Minutos'), ('3', '30 Minutos'), ('4', '1 Hora'), ('5', 'Nunca')], default='5', max_length=1)),
                ('tipo_contrasenia', models.CharField(choices=[('1', 'Mínimo 10 carácteres / contener números, mayúsculas, carácter especial'), ('2', 'Mínimo 8 carácteres / contener números, mayúsculas'), ('3', 'Mínimo 8 carácteres / contener sólo letras'), ('4', 'Mínimo 6 carácteres / contener sólo letras'), ('5', 'Mínimo 4 carácteres ')], default='5', max_length=1)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Políticas de Seguridad',
                'ordering': ['id_politica'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.departamento')),
            ],
            options={
                'verbose_name_plural': 'Puestos',
                'ordering': ['id_puesto'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellidos')),
                ('ip_ultimo_acceso', models.CharField(blank=True, max_length=50)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_modificacion', models.DateTimeField(null=True)),
                ('fch_cambio_password', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('primer_ingreso', models.IntegerField(blank=True, default=1, null=True)),
                ('cambiar_contrasenia', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='1', max_length=1)),
                ('bloqueado', models.CharField(choices=[('1', 'Bloqueado'), ('0', 'Desbloqueado')], default='0', max_length=1)),
                ('img_user', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Imagen de Perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.departamento', verbose_name='Departamento')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.puesto', verbose_name='Puesto')),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='User.perfil_usuario', verbose_name='Perfil de Usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('ver', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='1', max_length=1)),
                ('actualizar', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('crear', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('borrar', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_pantalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.pantalla', verbose_name='Pantalla')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.perfil_usuario', verbose_name='Perfil de Usuario')),
            ],
            options={
                'verbose_name_plural': 'Permisos',
                'ordering': ['id_permiso'],
            },
        ),
    ]
