# Generated by Django 4.1.2 on 2022-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica_seguridad',
            name='intentos_fallidos_login',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intentos_fallidos_login',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
