# Generated by Django 4.1.2 on 2022-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_fch_ingreso_labores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica_seguridad',
            name='permitir_sesion_duplicada',
            field=models.BooleanField(choices=[(False, 'Si'), (True, 'No')], default=False),
        ),
    ]
