# Generated by Django 4.1.2 on 2022-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('sistemaoperativo', models.CharField(blank=True, max_length=255, null=True)),
                ('pantalla_afectada', models.CharField(blank=True, max_length=255, null=True)),
                ('DB_afectada', models.CharField(blank=True, max_length=255, null=True)),
                ('tabla_afectada', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_afectado', models.CharField(blank=True, max_length=255, null=True)),
                ('id_registro_afectado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Acción')),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('dato_viejo', models.CharField(blank=True, max_length=255, null=True)),
                ('dato_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('otra_accion', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_log', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bitácora',
                'ordering': ['id'],
            },
        ),
    ]
